Reorganise files into classes (up to Run_Categorisation)
dolphin-acoustics-vip/artwarp pull request #40
Opened 2023-02-20 14:30 UTC by harvard-tham

2023-03-07 10:59 UTC, lixitrixi approved these changes
New organization looks good: "Old Classes" will act as an archive of the old version and we can copy code from there as we need it.

2023-03-07 21:20 UTC, olexandr-konovalov commented on README.md
> +# ARTwarp
This looks strange - it should not show all differences in lines 1-16 which are untouched. Which editor and which operating system do you use? How do you make commits?

2023-03-07 21:20 UTC, olexandr-konovalov commented on README.md
> +## Old Classes
I wonder if this is the right way to do this. Maybe you should have started another branch instead? Michael's code will be there under version control anyway at least for a while, until we decide to keep that  branch or delete it)

2023-03-07 21:25 UTC, olexandr-konovalov commented
> New organization looks good: "Old Classes" will act as an archive of the old version and we can copy code from there as we need it.
@lixitrixi sounds like replacing version control by shuffling files around - I am not convinced that this is what we needed.

Sometimes I am visited by an idea that we need to create a repository artwarp2 and work on a new version there from scratch. I haven't seen this coming last year, but now, when you completely change the architecture, that may be more viable...

2023-03-07 21:27 UTC, olexandr-konovalov reviewed
@harvard-tham can you figure out how to add some unit or script test? I want that to be able to use some actual tests with https://github.com/dolphin-acoustics-vip/artwarp/pull/43

2023-03-07 21:29 UTC, lixitrixi commented
> > New organization looks good: "Old Classes" will act as an archive of the old version and we can copy code from there as we need it.
> > @lixitrixi sounds like replacing version control by shuffling files around - I am not convinced that this is what we needed.
> 
> Sometimes I am visited by an idea that we need to create a repository artwarp2 and work on a new version there from scratch. I haven't seen this coming last year, but now, when you completely change the architecture, that may be more viable...

Now that you suggest it... I think this would be a good course of action.

2023-03-09 18:51 UTC, olexandr-konovalov commented
@lixitrixi now, after we are done with #26, perhaps we don't need a new repository after all! This way, we can publicise https://github.com/dolphin-acoustics-vip/artwarp/wiki as ARTWarp website and the URL seems hopefully to be stable enough for now.

The plan is that we have now a `stable-1` branch with ARTwarp v1.0 released from it. In case of any minor fixes needed, they should be made there, and we can release from that branch v1.1, v1.2 etc.

In the meantime, we work in the main branch here on ARTwarp v2.0. As soon as it stabilises, we create `stable-2` branch and from there will be making v2.0, v2.1 etc., and continuing to work in `main` on what could become eventually v3.0 in the same way.

Therefore, for new developments it will be simpler, as you don't have to keep all work in the 'rewrite' branch.

2023-03-13 21:24 UTC, olexandr-konovalov requested changes
Can't be merged in the present form. @harvard-tham and me will discuss tomorrow.

2023-03-14 11:47 UTC, olexandr-konovalov approved these changes

2023-03-14 11:47 UTC, merged