Comments for next semester's dev team, worked on network structure
dolphin-acoustics-vip/artwarp pull request #49
Opened 2023-04-03 14:15 UTC by lixitrixi

Michael and I discussed possible Network structures, and added comments to reflect ARTwarp goals for those working on the project next year.

2023-04-03 14:24 UTC, olexandr-konovalov commented
@lixitrixi please investigate failing unit tests

2023-04-07 13:05 UTC, lixitrixi commented
I will wait for @michaelstanway's recent pull request to be merged, then add the comments from this commit to the changed files to avoid unnecessary conflicts.

@olexandr-konovalov

2023-04-08 13:18 UTC, harvard-tham commented
the error is a simple change in the unit test from weight to weights. Can i checkout this or does it have to be Felix that changes it.

2023-04-08 13:20 UTC, harvard-tham commented on Category.m
> -            cat.average  = ContourFactory.getAverage(contours);
`ContourFactory` doesn't have `.getAverage( )` yet. Are you sure we want to have that in there?

2023-04-08 13:22 UTC, harvard-tham commented on Network.m
> +        weights
this is what caused the unit test to fail

2023-04-08 13:23 UTC, harvard-tham requested changes
Update the Network unit test to match the updated attribute

2023-04-08 14:05 UTC, harvard-tham commented
found out how to push to your fork, should work now

2023-04-08 14:06 UTC, harvard-tham approved these changes

2023-04-18 08:25 UTC, olexandr-konovalov requested changes
Thanks, @harvard-tham, for fixing tests.

@lixitrixi you should minimise putting unrelated things into same PR. CLI stuff could be easily done as a separate PR and one would not hold the other. It would also ease rebasing. For example, I could squash your changes and @harvard-tham's fix, to make a commit atomic. But now there is your CLI commit in the middle, which also needs fixing the commit message. It has unmatched `)` but is also written not clearly - what do you mean by " must be rewritten to work with new backend"? Is that work in progress? Moreover should be separate PR. Or is it for the current backend and later would have to be rewritten - in this case that should rather be said in the further text of the commit message, rather then in the 1st line.

2023-04-18 08:28 UTC, olexandr-konovalov commented
@lixitrixi requested changes - would be nice to address them and merge this ASAP. I don't think #50 is quite ready yet.

By the way, use the `#<PR number>` syntax for cross-referencing, rather than saying "@michaelstanway's recent pull request".

2023-04-19 13:41 UTC, olexandr-konovalov commented
@lixitrixi P.S. and of course if the CLI code is runnable, the CI already is ready to run it on GitHub actions. If not runnable, then not mergeable. So that should be really a separate PR. Would you like me to refactor it, or would you do it yourself? You need to create a new branch, cherry-pick the CLI commit there, then go back to the branch for this PR and rebase it to remove the CLI commit. BTW, you again submit a PR from your `rewrite`, forgetting to create a feature branch - one more argument to push for merging rewrite into main, but we can't do it as we are keeping adding stuff and it becomes hard to sync moving targets.

2023-05-20 13:25 UTC, olexandr-konovalov commented
What's the plan here? Unless anyone wishes to do this, I will take out @lixitrixi's CLI into a separate unmerged PR, and squash and merge the rest.

2023-05-20 13:32 UTC, lixitrixi commented
@olexandr-konovalov I apologize for the problems, I will CLI code into a separate PR as soon as I can. I am currently settling back into life at home, but I will find some time this week! I the CLI is completely separate, so it will be easy to make them separate.

2023-05-20 13:59 UTC, olexandr-konovalov commented
@lixitrixi thanks, sounds good, take your time then - will look here in a couple of weeks!

2023-06-15 01:13 UTC, lixitrixi commented
@olexandr-konovalov Sorry for the extended hiatus...

I have removed CLI-related files from this PR, and will add them to a separate PR after refactoring and making the code more complete. Just to confirm, you mean that I should create a separate feature branch on my fork for CLI code? As in: dolphin-acoustics-vip:rewrite <- lixitrixi:CLI-code (or similar) ?

2023-06-17 20:01 UTC, lixitrixi commented
The PR adding CLI code is ready on my fork, just waiting on this to be merged since that PR currently includes all the changes in this one as well.

2023-06-29 12:03 UTC, merged

2023-06-29 12:04 UTC, olexandr-konovalov commented
Thanks @lixitrixi - there could be a better way to refactor the PR then deleting files, but to save time I have just squashed and merge it instead of another refactoring.

2023-06-29 12:35 UTC, olexandr-konovalov commented
@lixitrixi now #46 merged and you can proceed with adding CLI. However, I am afraid that it's now based on the wrong branch. From now on, contributions are done not to the `rewrite` branch but to `main` (easier). For any change, pull the latest state of `main`, create a branch off it, add a change, submit a PR from it.